apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
data:
  neo4j_uri: bolt://neo4j-service:7687
  neo4j_username: neo4j
---
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secret
data:
  neo4j_auth: bmVvNGovMTIzNDU2Nzg= #neo4j/12345678
