apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: adminfront

build:
  artifacts:
    - image: adminfront
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - ./kubernetes
