apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:21.1.1
          args:
            - "start-dev"
          env:

            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: keycloak_admin

            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak_admin_password

            - name: KC_DB
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc_db

            - name: KC_DB_URL_HOST
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc_db_url_host

            - name: KC_DB_URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_db

            - name: KC_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user

            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres_password

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - protocol : TCP
      port: 8080
      targetPort: 8080
