apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: authlistener

build:
  artifacts:
    - image: authlistener
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - ./kubernetes/
