apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
    email: email@hehe.hehe
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  password: MTIzNA== # 1234
