apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml

configMapGenerator:
- name: keycloak-realm-conf
  files:
    - clientapp-realm.json
    - adminapp-realm.json
