apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
  - config.yml
patches:
  - path: config.yml
    target:
      kind: ConfigMap
      name: ingress-nginx-controller
      namespace: ingress-nginx
