apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgres_db: dbkeycloak 
  postgres_user: dbuser
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  postgres_password: MTIzNA== #1234
