apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - --address 
            - ":80"
            - /data
            - --console-address
            - ":9001"
          env:

            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: minio_root_user
                  
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: minio_root_password

          volumeMounts:
            - name: storage
              mountPath: /data
        - name: bucket-setup
          image: minio/mc
          command: ["sh", "/scripts/bucket-setup.sh"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: minio_root_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: minio_root_password
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: bucket-settings
              mountPath: /etc/bucket-settings
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pvc
        - name: bucket-settings
          configMap:
            name: bucket-settings
        - name: scripts
          configMap:
            name: minio-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
    - name: minio
      port: 80
      targetPort: 80
    - name: minio-console
      port: 9001
      targetPort: 9001
