apiVersion: v1
kind: ConfigMap
metadata:
  name: authlistener-config
data:
  rabbit_host: keycloak-rabbitmq-service
  neo4j_uri: bolt://neo4j-deployment-lb-neo4j:7687
  neo4j_username: neo4j
---
apiVersion: v1
kind: Secret
metadata:
  name: authlistener-secret
data:
  neo4j_auth: aGFoYWhlaGU= #hahahehe
