apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminback-deployment
spec:
  selector:
    matchLabels:
      app: adminback
  template:
    metadata:
      labels:
        app: adminback
    spec:
      containers:
        - name: adminback
          image: adminback
          imagePullPolicy: Never
          env:

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo_database

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: adminback-config
                  key: db_host

            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo_root_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_root_password
                  
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: clientback-config
                  key: db_host
                  
            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql_database
            
            - name: MYSQL_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql_user
            
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_password
                  
            - name: RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  name: clientback-config
                  key: rabbit_host

            - name: RABBIT_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: clientback-config
                  key: rabbit_queue

            - name: RABBIT_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: clientback-config
                  key: rabbit_class
            
            - name: ISSUER_URL
              valueFrom:
                configMapKeyRef:
                  name: adminback-config
                  key: issuer_url
            
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: minio_root_user
                  
            - name: MINIO_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: minio_root_password
            
            - name: MINIO_URL
              valueFrom:
                configMapKeyRef:
                  name: clientback-config
                  key: minio_url
            
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: clientback-config
                  key: minio_bucket
            
            - name: JAEGER_URL
              value: "http://jaeger-collector:14268/api/traces"
            - name: APP_NAME
              value: "adminback"
---
apiVersion: v1
kind: Service
metadata:
  name: adminback-service
spec:
  type: LoadBalancer
  selector:
    app: adminback
  ports:
    - port: 8080
      targetPort: 8080

