apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  proxy-buffer-size: "128k"
  proxy-buffers: "8 256k"
  proxy-busy-buffers-size: "256k"
  client-body-buffer-size: "256m"  
  proxy-body-size: "0"