apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: clientback
build:
  artifacts:
    - image: clientback
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - ./kubernetes/
