apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          env:

          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongo-express-config
                key: me_host

          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo_root_username

          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo_root_password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
    type: LoadBalancer
    selector:
      app: mongo-express
    ports:
      - port: 8081
        targetPort: 8081
